### ISSUE TITLE
Group by Syllabus Major Version in Report view

### ISSUE THREAD

**Issue by asiiim** [bishalgit/knowledge-syllabus#34]

**Comment by asiiim** [comment]
There issue in solving it as per the trace mentioned below:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\nerku\odoo11\odoo\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\nerku\odoo11\odoo\odoo\modules\loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "D:\nerku\odoo11\odoo\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\nerku\odoo11\odoo\odoo\modules\loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "D:\nerku\odoo11\odoo\odoo\modules\registry.py", line 277, in setup_models
    model._setup_fields()
  File "D:\nerku\odoo11\odoo\odoo\models.py", line 2425, in _setup_fields
    field.setup_full(self)
  File "D:\nerku\odoo11\odoo\odoo\fields.py", line 471, in setup_full
    self._setup_related_full(model)
  File "D:\nerku\odoo11\odoo\odoo\fields.py", line 508, in _setup_related_full
    field = target._fields[name]
KeyError: 'syllabus_version'
2018-11-04 10:42:08,720 31576 INFO syllabus werkzeug: 127.0.0.1 - - [04/Nov/2018 10:42:08] "POST /web/webclient/version_info HTTP/1.1" 500 -
2018-11-04 10:42:08,730 31576 ERROR syllabus werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Users\Asiiim\AppData\Local\Programs\Python\Python35\lib\site-packages\werkzeug\serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "C:\Users\Asiiim\AppData\Local\Programs\Python\Python35\lib\site-packages\werkzeug\serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "D:\nerku\odoo11\odoo\odoo\service\server.py", line 252, in app
    return self.app(e, s)
  File "D:\nerku\odoo11\odoo\odoo\service\wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "D:\nerku\odoo11\odoo\odoo\service\wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "D:\nerku\odoo11\odoo\odoo\http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "D:\nerku\odoo11\odoo\odoo\http.py", line 1292, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Users\Asiiim\AppData\Local\Programs\Python\Python35\lib\site-packages\werkzeug\wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "D:\nerku\odoo11\odoo\odoo\http.py", line 1473, in dispatch
    odoo.registry(db).check_signaling()
  File "D:\nerku\odoo11\odoo\odoo\__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "D:\nerku\odoo11\odoo\odoo\modules\registry.py", line 61, in __new__
    return cls.new(db_name)
  File "D:\nerku\odoo11\odoo\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "D:\nerku\odoo11\odoo\odoo\modules\loading.py", line 376, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "D:\nerku\odoo11\odoo\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "D:\nerku\odoo11\odoo\odoo\modules\loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "D:\nerku\odoo11\odoo\odoo\modules\registry.py", line 277, in setup_models
    model._setup_fields()
  File "D:\nerku\odoo11\odoo\odoo\models.py", line 2425, in _setup_fields
    field.setup_full(self)
  File "D:\nerku\odoo11\odoo\odoo\fields.py", line 471, in setup_full
    self._setup_related_full(model)
  File "D:\nerku\odoo11\odoo\odoo\fields.py", line 508, in _setup_related_full
    field = target._fields[name]
KeyError: 'syllabus_version'



What i was going to do was, i tried to create related field of syllabus_id of document.page.history. that related field is of Char. But i got above error.

**Comment by asiiim** [comment]
@bishalgit  @Siddhant-Pageni , any reason behind it?

**Comment by asiiim** [comment]
Major version are filterable only in syllabus history view.
